#!/usr/bin/with-contenv sh

SSMGR_TYPE=${SSMGR_TYPE:-"client"}
REDIS_PASS=${REDIS_PASS:-"123123321"}

if [ $SSMGR_TYPE != "client" ];then
    # disable hugepage
    if test -f /sys/kernel/mm/transparent_hugepage/khugepaged/defrag && test -w /sys/kernel/mm/transparent_hugepage/khugepaged/defrag; then
    echo 0 > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
    fi
    if test -f /sys/kernel/mm/transparent_hugepage/defrag && test -w /sys/kernel/mm/transparent_hugepage/defrag; then
    echo never > /sys/kernel/mm/transparent_hugepage/defrag
    fi
    if test -f /sys/kernel/mm/transparent_hugepage/enabled && test -w /sys/kernel/mm/transparent_hugepage/enabled; then
    echo never > /sys/kernel/mm/transparent_hugepage/enabled
    fi
    exec s6-setuidgid redis redis-server /etc/redis/redis.conf --requirepass $REDIS_PASS
fi

