#!/usr/bin/with-contenv sh

SSMGR_TYPE=${SSMGR_TYPE:-"client"}

ssPath="/root/.ssmgr/ss.yml"
webguiPath="/root/.ssmgr/webgui.yml"

cd /ssmgr
if [ $SSMGR_TYPE == "client" ];then
        exec node server.js -c $ssPath
else
        exec node server.js -c $webguiPath
fi