#!/usr/bin/with-contenv sh

SSMGR_PORT=${SSMGR_PORT:-"4001"}
SSMGR_PASSWORD=${SSMGR_PASSWORD:-"123456"}

cat > /root/.ssmgr/ss.yml <<-EOF
type: s
empty: false
shadowsocks:
  address: 127.0.0.1:4000
manager:
  address: 0.0.0.0:${SSMGR_PORT}
  password: '${SSMGR_PASSWORD}'
db: 'ss.sqlite'
EOF
